export const countries = ["Pakistan", "India", "China", "Iran", "Afghanistan"];

export const states = {
  Pakistan: [
    "Punjab",
    "Sindh",
    "Balochistan",
    "Khyber Pakhtunkhwa",
    "Gilgit-Baltistan",
    "Azad Kashmir",
  ],
  India: [
    "Uttar Pradesh",
    "Maharashtra",
    "Bihar",
    "West Bengal",
    "Madhya Pradesh",
    "Tamil Nadu",
  ],
  China: ["Guangdong", "Shandong", "Henan", "Sichuan", "Jiangsu", "Hebei"],
  Iran: [
    "Tehran",
    "Mazandaran",
    "Isfahan",
    "Fars",
    "Khuzestan",
    "East Azerbaijan",
  ],
  Afghanistan: ["Kabul", "Herat", "Kandahar", "Balkh", "Nangarhar", "Helmand"],
};

export const cities = {
  Punjab: ["Lahore", "Faisalabad", "Rawalpindi", "Multan"],
  Sindh: ["Karachi", "Hyderabad", "Sukkur", "Larkana"],
  Balochistan: ["Quetta", "Gwadar", "Khuzdar", "Turbat"],
  "Khyber Pakhtunkhwa": ["Peshawar", "Abbottabad", "Mardan", "Swat"],
  "Gilgit-Baltistan": ["Gilgit", "Skardu"],
  "Azad Kashmir": ["Muzaffarabad", "Mirpur", "Kotli"],
  "Uttar Pradesh": ["Lucknow", "Kanpur", "Agra", "Varanasi"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik"],
  Bihar: ["Patna", "Gaya", "Bhagalpur", "Muzaffarpur"],
  "West Bengal": ["Kolkata", "Asansol", "Siliguri", "Durgapur"],
  "Madhya Pradesh": ["Indore", "Bhopal", "Jabalpur", "Gwalior"],
  "Tamil Nadu": ["Chennai", "Coimbatore", "Madurai", "Tiruchirappalli"],
  Guangdong: ["Guangzhou", "Shenzhen", "Dongguan", "Foshan"],
  Shandong: ["Jinan", "Qingdao", "Yantai", "Weifang"],
  Henan: ["Zhengzhou", "Luoyang", "Kaifeng", "Anyang"],
  Sichuan: ["Chengdu", "Mianyang", "Luzhou", "Deyang"],
  Jiangsu: ["Nanjing", "Suzhou", "Wuxi", "Changzhou"],
  Hebei: ["Shijiazhuang", "Tangshan", "Baoding", "Handan"],
  Tehran: ["Tehran", "Karaj", "Eslamshahr", "Shahr-e Rey"],
  Mazandaran: ["Sari", "Babolsar", "Amol", "Behshahr"],
  Isfahan: ["Isfahan", "Kashan", "Najafabad", "Shahin Shahr"],
  Fars: ["Shiraz", "Marvdasht", "Kazerun", "Lar"],
  Khuzestan: ["Ahvaz", "Abadan", "Andimeshk", "Dezful"],
  "East Azerbaijan": ["Tabriz", "Maragheh", "Marand", "Osku"],
  Kabul: ["Kabul", "Khair Khana", "Deh Sabz", "Karte Parwan"],
  Herat: ["Herat", "Ghoryan", "Injil", "Kushk"],
  Kandahar: ["Kandahar", "Daman", "Arghandab", "Zhari"],
  Balkh: ["Mazar-e Sharif", "Balkh", "Dihdadi", "Kishindih"],
  Nangarhar: ["Jalalabad", "Behsud", "Kama", "Khogyani"],
  Helmand: ["Lashkar Gah", "Gereshk", "Sangin", "Nad Ali"],
};
